services:
  mysql8:
    container_name: mysql8
    image: mysql:8
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: sasa
      MYSQL_DATABASE: msvc_usuarios
    volumes:
      - data-mysql:/var/lib/mysql
    restart: always
    networks:
      - spring-cur-usu

  msvc-usuarios:
    container_name: msvc-usuarios
    image: alejo01478/usuarios:latest
#    image: msvc-usuarios
#    build:
#      context: ./
#      dockerfile: ./msvc-usuarios/Dockerfile
    ports:
      - "8001:8001"
    environment:
      PORT: 8001
      DB_HOST: mysql8:3306
      DB_DATABASE: msvc_usuarios
      DB_USERNAME: root
      DB_PASS: sasa
      CURSOS_URL: msvc-cursos:8002
    networks:
      - spring-cur-usu
    depends_on:
      - mysql8
#    restart: always

volumes:
  data-mysql:
    name: data-mysql

networks:
  spring-cur-usu:
    name: spring-cur-usu